# Generated by Django 5.0.1 on 2024-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resourcepacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(default=0, max_length=128)),
            ],
            options={
                'verbose_name': 'Ресурспак',
                'verbose_name_plural': 'Ресурспаки',
            },
        ),
    ]
